---
language: ruby
cache: bundler
rvm:
  - 2.2.4
services:
  - memcached
before_script:
  - psql -c 'create database gender_crowdsourcing_test;' -U postgres
  - bundle exec rake db:migrate
  - cp .env.example .env
