---
- Great stuff!
- Great job!
- Go you!
- Keep on sorting!
- You’re doing great work!
- Excellent work, thank you!
- Awesome work, thank you!
- Sterling work. Keep it up!
- Have a biscuit, you deserve it.
- High five! You’re doing great.
- You’re sorting up a storm!
- You’re the tops at gender sorting!
- Keep it up. Make a difference!
- Thanks! Your data makes a difference.
- Researchers will love that data!
- Journalists will love that data!
- One more? It’s for a good cause!
- And another? It’s for a good cause!
- w00t, check you out!
- Hippity hoppity, don’t you stoppity!
- Wowsers, you’re good at this.
- Srsly good stuff, yo.
